# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PR_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1024, 700)
        self.centralwidget = QtGui.QWidget(Form)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 100, 160, 444))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_syspara = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_syspara.setObjectName(_fromUtf8("verticalLayout_syspara"))
        self.label_NA = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_NA.setObjectName(_fromUtf8("label_NA"))
        self.verticalLayout_syspara.addWidget(self.label_NA)
        self.lineEdit_NA = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_NA.setObjectName(_fromUtf8("lineEdit_NA"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_NA)
        self.label_nfrac = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_nfrac.setObjectName(_fromUtf8("label_nfrac"))
        self.verticalLayout_syspara.addWidget(self.label_nfrac)
        self.lineEdit_nfrac = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_nfrac.setObjectName(_fromUtf8("lineEdit_nfrac"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_nfrac)
        self.label_objfl = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_objfl.setObjectName(_fromUtf8("label_objfl"))
        self.verticalLayout_syspara.addWidget(self.label_objfl)
        self.lineEdit_objfl = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_objfl.setObjectName(_fromUtf8("lineEdit_objfl"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_objfl)
        self.label_wlc = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_wlc.setObjectName(_fromUtf8("label_wlc"))
        self.verticalLayout_syspara.addWidget(self.label_wlc)
        self.lineEdit_wlc = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_wlc.setObjectName(_fromUtf8("lineEdit_wlc"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_wlc)
        self.label_nwl = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_nwl.setObjectName(_fromUtf8("label_nwl"))
        self.verticalLayout_syspara.addWidget(self.label_nwl)
        self.lineEdit_nwl = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_nwl.setObjectName(_fromUtf8("lineEdit_nwl"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_nwl)
        self.label_wlstep = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_wlstep.setObjectName(_fromUtf8("label_wlstep"))
        self.verticalLayout_syspara.addWidget(self.label_wlstep)
        self.lineEdit_wlstep = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_wlstep.setObjectName(_fromUtf8("lineEdit_wlstep"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_wlstep)
        self.label_pxl = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_pxl.setObjectName(_fromUtf8("label_pxl"))
        self.verticalLayout_syspara.addWidget(self.label_pxl)
        self.lineEdit_pxl = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_pxl.setObjectName(_fromUtf8("lineEdit_pxl"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_pxl)
        self.label_dz = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_dz.setObjectName(_fromUtf8("label_dz"))
        self.verticalLayout_syspara.addWidget(self.label_dz)
        self.lineEdit_zstep = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_zstep.setObjectName(_fromUtf8("lineEdit_zstep"))
        self.verticalLayout_syspara.addWidget(self.lineEdit_zstep)
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 90, 745, 421))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_display = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_display.setObjectName(_fromUtf8("gridLayout_display"))
        self.label_psfview = QtGui.QLabel(self.gridLayoutWidget)
        self.label_psfview.setObjectName(_fromUtf8("label_psfview"))
        self.gridLayout_display.addWidget(self.label_psfview, 0, 0, 1, 1)
        self.label_pupilview = QtGui.QLabel(self.gridLayoutWidget)
        self.label_pupilview.setObjectName(_fromUtf8("label_pupilview"))
        self.gridLayout_display.addWidget(self.label_pupilview, 0, 1, 1, 1)
        self.graphicsView_psf = QtGui.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_psf.sizePolicy().hasHeightForWidth())
        self.graphicsView_psf.setSizePolicy(sizePolicy)
        self.graphicsView_psf.setObjectName(_fromUtf8("graphicsView_psf"))
        self.gridLayout_display.addWidget(self.graphicsView_psf, 1, 0, 1, 1)
        self.graphicsView_pupil = QtGui.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_pupil.setObjectName(_fromUtf8("graphicsView_pupil"))
        self.gridLayout_display.addWidget(self.graphicsView_pupil, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_yzview = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yzview.sizePolicy().hasHeightForWidth())
        self.pushButton_yzview.setSizePolicy(sizePolicy)
        self.pushButton_yzview.setObjectName(_fromUtf8("pushButton_yzview"))
        self.horizontalLayout.addWidget(self.pushButton_yzview)
        self.pushButton_xyview = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_xyview.sizePolicy().hasHeightForWidth())
        self.pushButton_xyview.setSizePolicy(sizePolicy)
        self.pushButton_xyview.setObjectName(_fromUtf8("pushButton_xyview"))
        self.horizontalLayout.addWidget(self.pushButton_xyview)
        self.pushButton_xzview = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_xzview.sizePolicy().hasHeightForWidth())
        self.pushButton_xzview.setSizePolicy(sizePolicy)
        self.pushButton_xzview.setObjectName(_fromUtf8("pushButton_xzview"))
        self.horizontalLayout.addWidget(self.pushButton_xzview)
        self.pushButton_lineview = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lineview.sizePolicy().hasHeightForWidth())
        self.pushButton_lineview.setSizePolicy(sizePolicy)
        self.pushButton_lineview.setObjectName(_fromUtf8("pushButton_lineview"))
        self.horizontalLayout.addWidget(self.pushButton_lineview)
        self.gridLayout_display.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_rm4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_rm4.setObjectName(_fromUtf8("checkBox_rm4"))
        self.horizontalLayout_3.addWidget(self.checkBox_rm4)
        self.pushButton_pfraw = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pfraw.sizePolicy().hasHeightForWidth())
        self.pushButton_pfraw.setSizePolicy(sizePolicy)
        self.pushButton_pfraw.setObjectName(_fromUtf8("pushButton_pfraw"))
        self.horizontalLayout_3.addWidget(self.pushButton_pfraw)
        self.pushButton_pffit = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pffit.sizePolicy().hasHeightForWidth())
        self.pushButton_pffit.setSizePolicy(sizePolicy)
        self.pushButton_pffit.setObjectName(_fromUtf8("pushButton_pffit"))
        self.horizontalLayout_3.addWidget(self.pushButton_pffit)
        self.pushButton_zbar = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zbar.sizePolicy().hasHeightForWidth())
        self.pushButton_zbar.setSizePolicy(sizePolicy)
        self.pushButton_zbar.setObjectName(_fromUtf8("pushButton_zbar"))
        self.horizontalLayout_3.addWidget(self.pushButton_zbar)
        self.gridLayout_display.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(200, 520, 537, 54))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_pfsave = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_pfsave.setObjectName(_fromUtf8("horizontalLayout_pfsave"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_pupilfname = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_pupilfname.setObjectName(_fromUtf8("label_pupilfname"))
        self.verticalLayout.addWidget(self.label_pupilfname)
        self.lineEdit_pupilfname = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_pupilfname.setObjectName(_fromUtf8("lineEdit_pupilfname"))
        self.verticalLayout.addWidget(self.lineEdit_pupilfname)
        self.horizontalLayout_pfsave.addLayout(self.verticalLayout)
        self.pushButton_pfbrowse = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pfbrowse.sizePolicy().hasHeightForWidth())
        self.pushButton_pfbrowse.setSizePolicy(sizePolicy)
        self.pushButton_pfbrowse.setObjectName(_fromUtf8("pushButton_pfbrowse"))
        self.horizontalLayout_pfsave.addWidget(self.pushButton_pfbrowse)
        self.pushButton_savepupil = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_savepupil.sizePolicy().hasHeightForWidth())
        self.pushButton_savepupil.setSizePolicy(sizePolicy)
        self.pushButton_savepupil.setObjectName(_fromUtf8("pushButton_savepupil"))
        self.horizontalLayout_pfsave.addWidget(self.pushButton_savepupil)
        self.pushButton_savefit = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_savefit.sizePolicy().hasHeightForWidth())
        self.pushButton_savefit.setSizePolicy(sizePolicy)
        self.pushButton_savefit.setObjectName(_fromUtf8("pushButton_savefit"))
        self.horizontalLayout_pfsave.addWidget(self.pushButton_savefit)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 29, 501, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_load = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_load.setObjectName(_fromUtf8("horizontalLayout_load"))
        self.pushButton_loadpsf = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadpsf.sizePolicy().hasHeightForWidth())
        self.pushButton_loadpsf.setSizePolicy(sizePolicy)
        self.pushButton_loadpsf.setObjectName(_fromUtf8("pushButton_loadpsf"))
        self.horizontalLayout_load.addWidget(self.pushButton_loadpsf)
        self.lineEdit_loadpsf = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_loadpsf.setObjectName(_fromUtf8("lineEdit_loadpsf"))
        self.horizontalLayout_load.addWidget(self.lineEdit_loadpsf)
        self.pushButton_retrieve = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_retrieve.sizePolicy().hasHeightForWidth())
        self.pushButton_retrieve.setSizePolicy(sizePolicy)
        self.pushButton_retrieve.setObjectName(_fromUtf8("pushButton_retrieve"))
        self.horizontalLayout_load.addWidget(self.pushButton_retrieve)
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Form.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Form)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Phase Retrieval", None))
        self.label_NA.setText(_translate("Form", "Numerical aperture", None))
        self.lineEdit_NA.setText(_translate("Form", "1.0", None))
        self.label_nfrac.setText(_translate("Form", "Refractive index", None))
        self.lineEdit_nfrac.setText(_translate("Form", "1.33", None))
        self.label_objfl.setText(_translate("Form", "Focal length (mm)", None))
        self.lineEdit_objfl.setText(_translate("Form", "9.0", None))
        self.label_wlc.setText(_translate("Form", "Wavelength (nm)", None))
        self.lineEdit_wlc.setText(_translate("Form", "515.0", None))
        self.label_nwl.setText(_translate("Form", "# wavelengths", None))
        self.lineEdit_nwl.setText(_translate("Form", "3", None))
        self.label_wlstep.setText(_translate("Form", "Wavelength steps (nm)", None))
        self.lineEdit_wlstep.setText(_translate("Form", "5.0", None))
        self.label_pxl.setText(_translate("Form", "Pixel size (nm)", None))
        self.lineEdit_pxl.setText(_translate("Form", "103", None))
        self.label_dz.setText(_translate("Form", "z step (micron)", None))
        self.lineEdit_zstep.setText(_translate("Form", "0.50", None))
        self.label_psfview.setText(_translate("Form", "PSF view", None))
        self.label_pupilview.setText(_translate("Form", "Retrieved pupil", None))
        self.pushButton_yzview.setText(_translate("Form", "x-z", None))
        self.pushButton_xyview.setText(_translate("Form", "x-y", None))
        self.pushButton_xzview.setText(_translate("Form", "x-z", None))
        self.pushButton_lineview.setText(_translate("Form", "line", None))
        self.checkBox_rm4.setText(_translate("Form", "remove 1-4", None))
        self.pushButton_pfraw.setText(_translate("Form", "Original", None))
        self.pushButton_pffit.setText(_translate("Form", "Fit", None))
        self.pushButton_zbar.setText(_translate("Form", "Z-bar", None))
        self.label_pupilfname.setText(_translate("Form", "Pupil file name", None))
        self.pushButton_pfbrowse.setText(_translate("Form", "Browse", None))
        self.pushButton_savepupil.setText(_translate("Form", "Save pupil", None))
        self.pushButton_savefit.setText(_translate("Form", "Save z-fit", None))
        self.pushButton_loadpsf.setText(_translate("Form", "Load psf...", None))
        self.pushButton_retrieve.setText(_translate("Form", "Retrieve!", None))

